# docker-compose.yml

version: '3.8'

services:
  batyr-backend:
    build: .
    container_name: batyr-backend
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./batyr-images:/batyr-images
      - ./storage:/storage
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - batyr-net

  redis:
    image: "redis:alpine"
    container_name: redis
    # (Опционально) Если хотите подключаться к Redis с вашего компьютера для отладки
    # ports:
    #   - "6379:6379"
    networks:
      - batyr-net

networks:
  batyr-net:
    driver: bridge

    