# docker-compose.yml
version: '3.8'

services:
  # --- Основной бэкенд для генерации фото ---
  batyr-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: batyr-backend
    volumes:
      - ./batyr-images:/app/batyr-images
      - ./storage:/app/storage
    env_file:
      - ./.env # Рекомендуется использовать явный путь
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - batyr-net
    restart: always

  # --- Сервис для AI-ассистента ---
  batyr-assistant:
    build:
      context: .
      dockerfile: assistant.Dockerfile
    container_name: batyr-assistant
    env_file:
      - ./.env # Рекомендуется использовать явный путь
    networks:
      - batyr-net
    restart: always

  # --- Сервис для Telegram бота ---
  telegram-bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    container_name: telegram-bot
    env_file:
      - ./.env # Рекомендуется использовать явный путь
    networks:
      - batyr-net
    restart: always

  # --- Сервис для карты батыров (Flask) ---
  batyr-map-data:
    build:
      context: ./map-service
      dockerfile: map.Dockerfile
    container_name: batyr-map-data
    
    # ✅ ИСПРАВЛЕНИЕ: Указываем явный путь к файлу .env в корне проекта.
    # Это решает проблему, когда Docker Compose не может найти файл.
    env_file:
      - ./.env 
      
    networks:
      - batyr-net
    restart: always

  # --- Сервис Redis ---
  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - batyr-net
    restart: always

  # --- Главный прокси-сервер Nginx ---
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - batyr-backend
      - batyr-assistant
      - batyr-map-data
    networks:
      - batyr-net
    restart: always

networks:
  batyr-net:
    driver: bridge